language: smalltalk
sudo: false

os:
- linux

install:
- pip install --user benchupload

smalltalk:
- Pharo-6.1
- Pharo-7.0

after_success:
 - python -mbenchupload --dir=$SMALLTALK_CI_BUILD

after_failure:
- python -mbenchupload --dir=$SMALLTALK_CI_BUILD
